name: Build Binaries

on: push

jobs:
  MacOS:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GCC and other packages
        run: brew install mesa-glu glew glfw coreutils gcc@11

      - name: Install SOIL
        run: |
          brew tap zmarcantel/libsoil
          brew install libsoil

      - name: Build code
        run: make all

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macOS binary release
          path: Hyper