name: Build Binaries

on: push

jobs:
  MacOS:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GCC and other packages
        run: brew install gcc@11 glfw3 glew

      - name: Install SOIL
        run: |
          git clone https://github.com/littlstar/soil
          (cd soil; make && make install)

      - name: Build code
        run: make all