name: Build Binaries

on: push

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            git
            base-devel
            tree
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-luajit
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-glm

      - shell: msys2 {0}
        name: Build code
        run: make all

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows Binary Release
          path: |
            texture1.png
            texture2.png
            shaders/Voxel/Common.glsl
            shaders/Voxel/Fragment.glsl
            shaders/Voxel/Vertex.glsl
            shaders/Dummy/Common.glsl
            shaders/Dummy/Fragment.glsl
            shaders/Dummy/Vertex.glsl
            Hyper.exe
            config.lua